version: '3.2'
services:
  activemq:
    restart: 'always'
    ports:
    - '61616:61616'
    - '61613:61613'
    - '8161:8161'
    - '9020:9020'
    image: gpuliyar/activemq-jmx
    container_name: activemq-jmx-container
    networks:
      infranet:
        aliases:
        - 'activemq-service'
  elastic_search:
    restart: 'always'
    ports:
    - '9200:9200'
    image: elasticsearch
    container_name: elasticsearch-container
    environment:
    - 'discovery.type=single-node'
    networks:
      infranet:
        aliases:
        - 'elasticsearch-service'
  es_exporter:
    restart: 'always'
    ports:
    - '9108:9108'
    image: justwatch/elasticsearch_exporter
    container_name: es-exporter-container
    command:
    - '-es.uri=http://elasticsearch-service:9200'
    depends_on:
    - elastic_search
    networks:
      infranet:
        aliases:
        - elasticsearch-exporter-service
  mongo:
    restart: 'always'
    ports:
    - '27017:27017'
    image: mongo
    container_name: mongo-container
    networks:
      infranet:
        aliases:
        - 'mongodb-service'
  mongo_exporter:
    restart: 'always'
    ports:
    - '9001:9001'
    image: gpuliyar/mongo-exporter
    container_name: mongo-exporter-container
    environment:
    - 'MONGO_SERVICE=mongodb-service'
    - 'MONGO_PORT=27017'
    depends_on:
    - mongo
    networks:
      infranet:
        aliases:
        - 'mongodb-exporter-service'
  grafana:
    restart: 'always'
    ports:
    - '3000:3000'
    image: grafana/grafana
    container_name: grafana-container
  prometheus:
    restart: 'always'
    ports:
    - '9090:9090'
    image: prom/prometheus
    container_name: prometheus-container
    command:
    - '--config.file=/prometheus/config/prometheus.yaml'
    - '--storage.tsdb.path=/data'
    volumes:
    - ./config:/prometheus/config
    - ./data:/data
    depends_on:
    - activemq
    - es_exporter
    - mongo_exporter
    networks:
      infranet:
        aliases:
        - 'prometheus-service'
networks:
  infranet:
